from turtle import *
shape('turtle')
fillcolor("green")
n = int(input("ban muon canh dai bao nhieu?"))
forward(int(n))
left(60)
forward(int(n))
left(60)
forward(int(n))
left(60)
forward(int(n))
left(60)
forward(int(n))
left(60)
forward(int(n))
mainloop()